apiVersion: v1
kind: BuildConfig
metadata:
  name: git-credentials
  labels:
    app: template-graphql-typescript
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/gsi-enablement-one/template-graphql-typescript.git'
      ref: dev
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-aus-beta
        - name: BRANCH
          value: dev
